# Generated by Django 2.2.13 on 2020-08-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edurep', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EdurepFile',
        ),
    ]
