# Generated by Django 3.2.14 on 2022-11-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanze', '0002_is_extracted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HanzeResearchObjectResource',
        ),
    ]
