# Generated by Django 2.2.18 on 2021-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_youtubethumnbailresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oaipmhset',
            name='repository',
            field=models.CharField(choices=[('edurep.EdurepOAIPMH', 'Edurep'),
                                            ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
    ]
