# Generated by Django 2.2.18 on 2021-03-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sharekit_repository'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OAIPMHSet',
            new_name='HarvestSource',
        ),
        migrations.RenameModel(
            old_name='OAIPMHHarvest',
            new_name='Harvest',
        ),
        migrations.AlterModelOptions(
            name='harvest',
            options={},
        ),
        migrations.AlterField(
            model_name='harvest',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.HarvestSource'),
        ),
        migrations.AlterModelOptions(
            name='harvestsource',
            options={},
        ),
        migrations.RemoveField(
            model_name='arrangement',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='arrangement',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='document',
            name='arrangement',
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harvestsource',
            name='spec',
            field=models.CharField(help_text="The code for the 'set' you want to harvest", max_length=255),
        ),
    ]
