# Generated by Django 2.2.18 on 2021-04-01 10:37

import core.models.harvest
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_harvest_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='purge_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvestsource',
            name='delete_policy',
            field=models.CharField(choices=[('no', 'No'), ('persistent', 'Persistent'), ('transient', 'Transient')], default='transient', max_length=50),
        ),
        migrations.AddField(
            model_name='harvestsource',
            name='purge_interval',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=core.models.harvest.thirty_days_default),
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=50)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='dataset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DatasetVersion'),
        ),
        migrations.AddField(
            model_name='document',
            name='dataset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DatasetVersion'),
        ),
        migrations.AddField(
            model_name='elasticindex',
            name='dataset_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='core.DatasetVersion'),
        ),
        migrations.AlterField(
            model_name='elasticindex',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='core.Dataset'),
        ),
    ]
