# Generated by Django 2.2.18 on 2021-04-01 10:37

from datetime import datetime, timedelta
from django.conf import settings
from django.db import migrations
from django.utils.timezone import make_aware


def migrate_dataset_data_to_dataset_version(apps, schema_editor):
    Dataset = apps.get_model("core.Dataset")
    DatasetVersion = apps.get_model("core.DatasetVersion")
    for dataset in Dataset.objects.all():
        # Creating a version from the dataset
        version = DatasetVersion.objects.create(dataset=dataset, is_current=True, version=settings.VERSION)
        # Migrating collections and documents
        for collection in dataset.collection_set.all():
            collection.dataset = None
            collection.dataset_version = version
            collection.save()
        for document in dataset.document_set.all():  # REFACTOR: speed up?
            document.dataset = None
            document.dataset_version = version
            document.save()
        # Migrating indices
        version.indices.add(*list(dataset.indices.all()))
        dataset.indices.clear()
        # Setting purge_after for harvests
        # We're assuming default delete policies
        for harvest in dataset.harvest_set.all():
            purge_delta = timedelta(**harvest.source.purge_interval)
            harvest.purge_after = make_aware(datetime.now() + purge_delta)
            harvest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_harvest_refactor'),
    ]

    operations = [
        migrations.RunPython(
            migrate_dataset_data_to_dataset_version,
            migrations.RunPython.noop
        )
    ]
