# Generated by Django 2.2.20 on 2021-04-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_harvest_refactor_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetversion',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='elasticindex',
            name='pushed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
