# Generated by Django 2.2.18 on 2021-04-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_harvest_refactor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetversion',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.Dataset'),
        ),
        migrations.AlterField(
            model_name='datasetversion',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
