# Generated by Django 2.2.20 on 2021-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sharekit_speedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='is_syncing',
            field=models.BooleanField(default=False),
        ),
    ]
