# Generated by Django 3.2.3 on 2021-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticindex',
            name='language',
            field=models.CharField(choices=[('en', 'english'), ('nl', 'dutch'), ('unk', 'standard')], max_length=5),
        ),
    ]
