# Generated by Django 3.2.4 on 2021-08-08 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pipeline_processors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(default=dict)),
                ('identity', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_parent', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collection')),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datasetversion')),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': 'id',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.extension'),
        ),
    ]
