# Generated by Django 3.2.4 on 2021-09-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_dynamic_extraction_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectiveproperty',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='objectiveproperty',
            name='json_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.jsonextractionfield'),
        ),
        migrations.AlterField(
            model_name='objectiveproperty',
            name='method_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.methodextractionfield'),
        ),
        migrations.AlterField(
            model_name='objectiveproperty',
            name='property',
            field=models.CharField(choices=[('external_id', 'external_id'), ('analysis_allowed', 'analysis_allowed'), ('lowest_educational_level', 'lowest_educational_level'), ('technical_type', 'technical_type'), ('publishers', 'publishers'), ('authors', 'authors'), ('is_restricted', 'is_restricted'), ('research_object_type', 'research_object_type'), ('material_types', 'material_types'), ('title', 'title'), ('copyright_description', 'copyright_description'), ('aggregation_level', 'aggregation_level'), ('has_parts', 'has_parts'), ('lom_educational_levels', 'lom_educational_levels'), ('mime_type', 'mime_type'), ('publisher_date', 'publisher_date'), ('files', 'files'), ('research_themes', 'research_themes'), ('is_part_of', 'is_part_of'), ('copyright', 'copyright'), ('parties', 'parties'), ('ideas', 'ideas'), ('doi', 'doi'), ('language', 'language'), ('disciplines', 'disciplines'), ('keywords', 'keywords'), ('url', 'url'), ('from_youtube', 'from_youtube'), ('description', 'description'), ('state', 'state')], max_length=50),
        ),
    ]
