# Generated by Django 3.2.4 on 2021-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_secure_dynamic_extraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionmapping',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('edurep.EdurepOAIPMH', 'Edurep'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='harvestsource',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('edurep.EdurepOAIPMH', 'Edurep'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
    ]
