# Generated by Django 3.2.8 on 2021-10-22 14:53

import datagrowth.configuration.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0023_thumbnails_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectiveproperty',
            name='property',
            field=models.CharField(choices=[('is_part_of', 'is_part_of'), ('is_restricted', 'is_restricted'), ('copyright', 'copyright'), ('lowest_educational_level', 'lowest_educational_level'), ('disciplines', 'disciplines'), ('publisher_date', 'publisher_date'), ('analysis_allowed', 'analysis_allowed'), ('material_types', 'material_types'), ('url', 'url'), ('has_parts', 'has_parts'), ('parties', 'parties'), ('research_themes', 'research_themes'), ('ideas', 'ideas'), ('authors', 'authors'), ('title', 'title'), ('mime_type', 'mime_type'), ('description', 'description'), ('copyright_description', 'copyright_description'), ('state', 'state'), ('technical_type', 'technical_type'), ('external_id', 'external_id'), ('aggregation_level', 'aggregation_level'), ('files', 'files'), ('from_youtube', 'from_youtube'), ('language', 'language'), ('keywords', 'keywords'), ('lom_educational_levels', 'lom_educational_levels'), ('doi', 'doi'), ('publishers', 'publishers'), ('research_object_type', 'research_object_type')], max_length=50),
        ),
        migrations.CreateModel(
            name='PdfThumbnailResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(db_index=True, default=None, max_length=255)),
                ('status', models.PositiveIntegerField(default=0)),
                ('config', datagrowth.configuration.fields.ConfigurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('retainer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_hash', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('request', models.JSONField(blank=True, default=None, null=True)),
                ('head', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('preview', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='core/previews/pdf')),
                ('retainer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
