# Generated by Django 3.2.8 on 2021-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pdf_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tikaresource',
            name='retainer_type',
        ),
        migrations.DeleteModel(
            name='FileResource',
        ),
        migrations.DeleteModel(
            name='TikaResource',
        ),
    ]
