# Generated by Django 3.2.5 on 2021-11-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_objectiveproperty_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extension',
            old_name='is_parent',
            new_name='is_addition',
        ),
    ]
