# Generated by Django 3.2.5 on 2021-12-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_matomo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.extension'),
        ),
        migrations.AlterField(
            model_name='extractionmapping',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('edurep.EdurepOAIPMH', 'Edurep'), ('hanze.HanzeResearchObjectResource', 'Hanze'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='harvestsource',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('edurep.EdurepOAIPMH', 'Edurep'), ('hanze.HanzeResearchObjectResource', 'Hanze'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
    ]
