# Generated by Django 3.2.8 on 2022-01-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_publisher_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChromeScreenshotResource',
        ),
    ]
