# Generated by Django 3.2.5 on 2022-02-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
