# Generated by Django 3.2.5 on 2022-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_dataset_version_simplification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionmapping',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('edurep.EdurepOAIPMH', 'Edurep'), ('sources.HanOAIPMHResource', 'Han'), ('hanze.HanzeResearchObjectResource', 'Hanze'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='harvestsource',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('edurep.EdurepOAIPMH', 'Edurep'), ('sources.HanOAIPMHResource', 'Han'), ('hanze.HanzeResearchObjectResource', 'Hanze'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
    ]
