# Generated by Django 3.2.12 on 2022-03-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_han_oaipmh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionmapping',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('edurep.EdurepOAIPMH', 'Edurep'), ('sources.HanOAIPMHResource', 'Han'), ('hanze.HanzeResearchObjectResource', 'Hanze'), ('sources.HvaPureResource', 'Hva'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='harvestsource',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('edurep.EdurepOAIPMH', 'Edurep'), ('sources.HanOAIPMHResource', 'Han'), ('hanze.HanzeResearchObjectResource', 'Hanze'), ('sources.HvaPureResource', 'Hva'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
    ]
