# Generated by Django 3.2.14 on 2022-09-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_disciplines_and_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticindex',
            name='educational_level',
            field=models.IntegerField(choices=[(1, 'Vocational Education'), (2, 'Applied Science'), (3, 'University')], default=2),
        ),
    ]
