# Generated by Django 3.2.14 on 2022-11-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0042_educational_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticindex',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
