# Generated by Django 3.2.14 on 2023-01-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_hanze_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodextractionfield',
            name='method',
        ),
        migrations.RemoveField(
            model_name='objectiveproperty',
            name='json_field',
        ),
        migrations.RemoveField(
            model_name='objectiveproperty',
            name='mapping',
        ),
        migrations.RemoveField(
            model_name='objectiveproperty',
            name='method_field',
        ),
        migrations.DeleteModel(
            name='ExtractionMapping',
        ),
        migrations.DeleteModel(
            name='ExtractionMethod',
        ),
        migrations.DeleteModel(
            name='JSONExtractionField',
        ),
        migrations.DeleteModel(
            name='MethodExtractionField',
        ),
        migrations.DeleteModel(
            name='ObjectiveProperty',
        ),
    ]
