# Generated by Django 3.2.14 on 2023-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_hanze_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionmapping',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('sources.BuasPureResource', 'Buas'), ('edurep.EdurepOAIPMH', 'Edurep'), ('sources.GreeniOAIPMHResource', 'Greeni'), ('sources.HanOAIPMHResource', 'Han'), ('sources.HanzeResearchObjectResource', 'Hanze'), ('sources.HkuMetadataResource', 'Hku'), ('sources.HvaPureResource', 'Hva'), ('sources.PublinovaMetadataResource', 'Publinova'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='harvestsource',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('sources.BuasPureResource', 'Buas'), ('edurep.EdurepOAIPMH', 'Edurep'), ('sources.GreeniOAIPMHResource', 'Greeni'), ('sources.HanOAIPMHResource', 'Han'), ('sources.HanzeResearchObjectResource', 'Hanze'), ('sources.HkuMetadataResource', 'Hku'), ('sources.HvaPureResource', 'Hva'), ('sources.PublinovaMetadataResource', 'Publinova'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
    ]
