# Generated by Django 3.2.16 on 2023-03-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_extract_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestsource',
            name='repository',
            field=models.CharField(choices=[('anatomy_tool.AnatomyToolOAIPMH', 'Anatomy_tool'), ('sources.BuasPureResource', 'Buas'), ('edurep.EdurepOAIPMH', 'Edurep'), ('sources.EdurepJsonSearchResource', 'Edurep_jsonsearch'), ('sources.GreeniOAIPMHResource', 'Greeni'), ('sources.HanOAIPMHResource', 'Han'), ('sources.HanzeResearchObjectResource', 'Hanze'), ('sources.HkuMetadataResource', 'Hku'), ('sources.HvaPureResource', 'Hva'), ('sharekit.SharekitMetadataHarvest', 'Sharekit')], max_length=50),
        ),
    ]
