# Generated by Django 2.0.6 on 2018-10-26 08:57

from django.db import migrations
import surf.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', surf.apps.users.models.UserManager()),
            ],
        ),
    ]
