# Generated by Django 2.0.6 on 2018-11-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_surfconextauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfconextauth',
            name='access_token',
            field=models.TextField(),
        ),
    ]
