# Generated by Django 2.0.10 on 2019-02-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_sharedresourcecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='applaud_count',
            field=models.IntegerField(default=0),
        ),
    ]
