# Generated by Django 2.0.13 on 2019-08-30 09:26

from django.db import migrations


def clone_disciplines_to_mptt(apps, schema_editor):
    Material = apps.get_model('materials', 'Material')
    MpttFilterItem = apps.get_model('filters', 'MpttFilterItem')
    vakgebied_root_node = MpttFilterItem.objects.get(external_id="lom.classification.obk.discipline.id")
    for material in Material.objects.all():
        disciplines = material.disciplines
        for discipline in disciplines.all():
            mpttfilteritem, created = MpttFilterItem.objects.get_or_create(name=discipline.title,
                                                                           parent=vakgebied_root_node)
            material.mptt_disciplines.add(mpttfilteritem)

        material.save()


def remove_mptt_disciplines(apps, schema_editor):
    Material = apps.get_model('materials', 'Material')
    for material in Material.objects.all():
        material.mptt_disciplines.clear()
        material.save()


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_material_mptt_disciplines'),
    ]

    operations = [
        migrations.RunPython(clone_disciplines_to_mptt, remove_mptt_disciplines)
    ]
