# Generated by Django 2.0.13 on 2019-08-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_remove_material_disciplines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='mptt_disciplines',
            new_name='disciplines',
        ),
    ]
