# Generated by Django 2.2.7 on 2020-01-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_auto_20191112_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedresourcecounter',
            name='counter_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
