# Generated by Django 2.0.13 on 2019-07-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locale', '0004_auto_20190724_0752'),
        ('themes', '0002_auto_20181207_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='title_translations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.Locale'),
        ),
    ]
