# Generated by Django 2.0.13 on 2019-08-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0008_auto_20190829_1437'),
        ('themes', '0003_improved_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='mptt_disciplines',
            field=models.ManyToManyField(blank=True, related_name='parent_themes', to='filters.MpttFilterItem'),
        ),
        migrations.AddField(
            model_name='theme',
            name='mptt_filter_category_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='filters.MpttFilterItem'),
        ),
    ]
