# Generated by Django 2.0.13 on 2019-07-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localeHTML', '0001_squashed_0002_auto_20190724_1002'),
        ('themes', '0003_theme_title_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description_translations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='localeHTML.LocaleHTML'),
        ),
    ]
