FORMAT: 1A
HOST: https://surf.mqd.me

# Surf

Surf API

## Errors

4xx errors are client errors, so the only way to handle them is to validate input data and repeat request.
5xx errors are server errors and should be handled with repeated requests.


# Group Materials

## SearchResult Resource [/api/v1/materials/search/]

### POST [POST /api/v1/materials/search/]

+ Request (application/json)

    + Headers

            Authorization: Token 77d4f58da328105d92d0a255780fcf3a6b51403c

    + Body

            {
                "search_text": ["some searched text"],
                "page": 1,
                "page_size": 5,
                "filters": [
                    {
                        "id": "lom.technical.format",
                        "items": [
                            "audio",
                            "video"
                        ]
                    },
                    {
                        "id": "lom.general.aggregationlevel",
                        "items": [
                            "1",
                            "3"
                        ]
                    }
                ],
                "ordering": "-lom.lifecycle.contribute.publisherdate",
                "author": "Material author",
                "return_records": true,
                "return_filters": true
            }


+ Response 200 (application/json)
    + Attributes (SearchResult)

## Keywords Resource [/api/v1/materials/keywords/]

### GET [GET /api/v1/materials/keywords/{?query}]

+ Parameters
  + query (string) - query string

+ Request (application/json)

    + Headers

            Authorization: Token 77d4f58da328105d92d0a255780fcf3a6b51403c

+ Response 200 (application/json)
    + Attributes (array[string])

# Data Structures

## Material (object)
 - id: `edurep_delen:887f1f83-b821-449e-9b08-c5571bcfbda2` (string) - material id in edurep
 - object_id: `urn:uuid:887f1f83-b821-449e-9b08-c5571bcfbda2` (string) - material URI
 - url: `http://delen.edurep.nl/download.php?id=887f1f83-b821-449e-9b08-c5571bcfbda2` (string) - material URL
 - title: `test1` (string) - title of material
 - description: `test` (string) - material description
 - keywords: (array[string]) - keywords for material
 - language: `nl` (string) - material language
 - aggregationlevel: `1` (string) - aggregation level of material
 - publisher: `wikiwijs_repository` (string) - publisher name
 - publish_datetime: `2018-09-19T01:08:08+02:00` (string) - publish datetime
 - author: `awar rashkany` (string) - author name
 - creator: `Mendy` (string) - creator name
 - format: `image` (string) - material technical format
 - number_of_ratings: `1` (number) - number of ratings for material
 - average_rating: `1.0` (number) - average ratings of material (from 0 to 5)

## FilterExtraDataItem (object)
 - id: `5e86dc82-1981-48df-bbe5-abd4a9b3767b` (string) - filter item id
 - count: `17143` (number) - found material count for filter item

## FilterExtraData (object)
 - id: `lom.classification.obk.discipline.id` (string) - filter category id
 - items: (array[FilterExtraDataItem]) - extra data for each filter item

## SearchResult (object)
 - records: (array[Material]) - found materials
 - filters: (array[FilterExtraData]) - found materials count for each filter item
 - page: `1` (number) - page number
 - page_size: `5` (number) - page size
 - records_total: `10000` (number) - total count of found materials
