version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...      
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t mqd-surf-backend .
      - docker tag mqd-surf-backend:latest 233549791968.dkr.ecr.eu-central-1.amazonaws.com/mqd-surf-backend:latest  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 233549791968.dkr.ecr.eu-central-1.amazonaws.com/mqd-surf-backend:latest
