# Generated by Django 2.0.6 on 2018-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_filter_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
