# Generated by Django 3.2.4 on 2021-08-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_manual_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttfilteritem',
            name='external_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Field in Elastic'),
        ),
    ]
