# Generated by Django 3.2.4 on 2021-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_external_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttfilteritem',
            name='external_id',
            field=models.CharField(max_length=255, verbose_name='Field in Elastic'),
        ),
        migrations.AlterUniqueTogether(
            name='mpttfilteritem',
            unique_together={('parent', 'external_id')},
        ),
    ]
