# Generated by Django 3.2.8 on 2022-03-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0005_elastic_filters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpttFilterItem',
        ),
    ]
