# Generated by Django 2.0.13 on 2019-11-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0011_auto_20190905_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtercategory',
            name='title_translations',
        ),
        migrations.RemoveField(
            model_name='filtercategoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='category_item',
        ),
    ]
