# Generated by Django 2.2.13 on 2020-07-02 10:05

from django.db import migrations


def remove_double_yes_filter_item(apps, schema_editor):
    MpttFilterItem = apps.get_model('filters', 'MpttFilterItem')
    yes_filter = MpttFilterItem.objects.filter(name='yes')[:1].values_list("id", flat=True)
    MpttFilterItem.objects.filter(name='yes').exclude(pk__in=list(yes_filter)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0013_auto_20191112_1040'),
    ]

    operations = [
        migrations.RunPython(remove_double_yes_filter_item)
    ]
