# Generated by Django 2.2.13 on 2020-09-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0014_auto_20200702_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteritem',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='mptt_category_item',
        ),
        migrations.AlterField(
            model_name='mpttfilteritem',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='mpttfilteritem',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='mpttfilteritem',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='FilterItem',
        ),
    ]
