# Generated by Django 2.2.13 on 2020-09-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0015_remove_user_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttfilteritem',
            name='external_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Field id in EduRep'),
        ),
    ]
