# Generated by Django 2.0.13 on 2019-12-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_custom_user_and_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surfconextauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='SurfConextAuth',
        ),
    ]
