CREATE SCHEMA IF NOT EXISTS public;

GRANT CONNECT ON DATABASE edushare TO django;
GRANT ALL PRIVILEGES ON DATABASE edushare TO django;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO django;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO django;

CREATE DATABASE harvester;
GRANT CONNECT ON DATABASE harvester TO django;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO django;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO django;
