#!/usr/bin/env bash


set -e


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER django WITH ENCRYPTED PASSWORD '${DJANGO_POSTGRES_PASSWORD}';
    ALTER USER django CREATEDB;
    GRANT CONNECT ON DATABASE edushare TO django;
    GRANT ALL PRIVILEGES ON DATABASE edushare TO django;
    ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO django;
    ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO django;

    CREATE DATABASE harvester;
    GRANT CONNECT ON DATABASE harvester TO django;
    GRANT ALL PRIVILEGES ON DATABASE harvester TO django;

EOSQL
