# Generated by Django 3.2.12 on 2022-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_greeni_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenioaipmhresource',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hanoaipmhresource',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hkumetadataresource',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hvapureresource',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
