# Generated by Django 2.0.10 on 2019-03-29 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset', models.CharField(max_length=512, unique=True, verbose_name='Asset ID')),
                ('en', models.CharField(blank=True, max_length=5120, null=True, verbose_name='English, en')),
                ('nl', models.CharField(blank=True, max_length=5120, null=True, verbose_name='Netherlands, nl-NL')),
            ],
            options={
                'verbose_name': 'textstring',
                'verbose_name_plural': 'Localization',
            },
        ),
    ]
