# Generated by Django 2.0.13 on 2019-07-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locale', '0003_fill_localizations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locale',
            options={'verbose_name': 'Localization', 'verbose_name_plural': 'Localizations'},
        ),
    ]
