# Generated by Django 3.2.8 on 2022-03-16 09:48

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import django_enumfield.db.fields
import surf.statusenums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filters', '0001_squashed_0016_filters_external_id_unique'),
        ('themes', '0001_squashed_0004_strip_themes_and_disciplines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, verbose_name='EduRep material id')),
                ('themes', models.ManyToManyField(blank=True, related_name='materials', to='themes.Theme')),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('material_url', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('disciplines', models.ManyToManyField(blank=True, related_name='materials', to='filters.MpttFilterItem')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('applaud_count', models.BigIntegerField(default=0)),
                ('star_1', models.PositiveIntegerField(default=0)),
                ('star_2', models.PositiveIntegerField(default=0)),
                ('star_3', models.PositiveIntegerField(default=0)),
                ('star_4', models.PositiveIntegerField(default=0)),
                ('star_5', models.PositiveIntegerField(default=0)),
                ('view_count', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedResourceCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter_key', models.CharField(max_length=255, unique=True)),
                ('counter_value', models.IntegerField(default=0)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_shared', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('publish_status', django_enumfield.db.fields.EnumField(default=0, enum=surf.statusenums.PublishStatus)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.collection')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
            options={
                'verbose_name': 'Material',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='collections', through='materials.CollectionMaterial', to='materials.Material'),
        ),
        migrations.AddConstraint(
            model_name='collectionmaterial',
            constraint=models.UniqueConstraint(fields=('collection', 'material'), name='unique materials in collection'),
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='title',
            new_name='title_nl',
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_nl',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_nl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionmaterial',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='material',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_url',
        ),
        migrations.RemoveField(
            model_name='material',
            name='title',
        ),
        migrations.AlterField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='material',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='material',
            name='themes',
        ),
    ]
