# Generated by Django 2.2.13 on 2021-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_new_sharekit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='material',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_url',
        ),
        migrations.RemoveField(
            model_name='material',
            name='title',
        ),
        migrations.AlterField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
