# Generated by Django 3.2.8 on 2021-12-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_sharekit_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='material',
            name='themes',
        ),
    ]
