# Generated by Django 2.0.6 on 2018-11-08 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_viewmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmaterial',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
