# Generated by Django 2.0.6 on 2018-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_auto_20181116_1253'),
        ('themes', '0001_initial'),
        ('materials', '0007_collection_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='materials', to='filters.FilterCategoryItem'),
        ),
        migrations.AddField(
            model_name='material',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='materials', to='themes.Theme'),
        ),
    ]
