# Generated by Django 2.0.6 on 2018-12-11 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20181205_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedResourceCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter_key', models.CharField(max_length=255)),
                ('counter_value', models.IntegerField(default=0)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
