# Generated by Django 2.0.13 on 2019-08-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0008_auto_20190829_1437'),
        ('materials', '0014_set_material_applaud_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='mptt_disciplines',
            field=models.ManyToManyField(blank=True, related_name='materials', to='filters.MpttFilterItem'),
        ),
    ]
