# Generated by Django 2.0.13 on 2019-08-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_auto_20190830_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='disciplines',
        ),
    ]
