# Generated by Django 2.0.13 on 2019-11-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_remove_old_collection_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applaudmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='applaudmaterial',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='viewmaterial',
            name='user',
        ),
        migrations.AddField(
            model_name='material',
            name='applaud_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='star_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='star_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='star_3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='star_4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='star_5',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ApplaudMaterial',
        ),
        migrations.DeleteModel(
            name='ViewMaterial',
        ),
    ]
