# Generated by Django 2.2.10 on 2020-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_auto_20200121_0828'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collectionmaterial',
            constraint=models.UniqueConstraint(fields=('collection', 'material'), name='unique materials in collection'),
        ),
    ]
