# Generated by Django 2.2.13 on 2020-07-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_update_meta_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
