# Generated by Django 2.2.13 on 2020-07-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_collection_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="title_nl",
            field=models.CharField(blank=True, max_length=80, null=True)
        ),
        migrations.AlterField(
            model_name="collection",
            name="title_en",
            field=models.CharField(blank=True, max_length=80, null=True)
        )
    ]
