# Generated by Django 2.2.13 on 2020-09-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_auto_20200714_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_nl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
