# Generated by Django 2.0.13 on 2019-07-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localeHTML', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localehtml',
            name='nl',
            field=models.TextField(blank=True, max_length=16384, null=True, verbose_name='Dutch, nl-NL'),
        ),
    ]
