# Generated by Django 3.2.3 on 2021-06-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharekit', '0001_sharekit_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharekitmetadataharvest',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sharekitmetadataharvest',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
