# Generated by Django 3.2.12 on 2022-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharekit', '0002_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharekitmetadataharvest',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
