# Generated by Django 2.0.13 on 2019-08-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20181210_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='The proportion of the image should be 388x227', null=True, upload_to='communities'),
        ),
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, help_text='The proportion of the image should be 230x136', null=True, upload_to='communities'),
        ),
    ]
