# Generated by Django 2.0.13 on 2019-11-04 09:39

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import surf.statusenums


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_auto_20191021_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='publish_status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=surf.statusenums.PublishStatus),
        ),
        migrations.AlterField(
            model_name='community',
            name='description_translations',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.LocaleHTML'),
        ),
        migrations.AlterField(
            model_name='community',
            name='title_translations',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.Locale'),
        ),
    ]
