# Generated by Django 2.2.7 on 2020-02-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_community_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='description',
        ),
        migrations.RemoveField(
            model_name='community',
            name='description_translations',
        ),
        migrations.RemoveField(
            model_name='community',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='community',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='community',
            name='title_translations',
        ),
        migrations.RemoveField(
            model_name='community',
            name='website_url',
        ),
        migrations.CreateModel(
            name='CommunityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=16384, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text='The proportion of the image should be 230x136', null=True, upload_to='communities')),
                ('featured_image', models.ImageField(blank=True, help_text='The proportion of the image should be 388x227', null=True, upload_to='communities')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community')),
            ],
        ),
        migrations.AddConstraint(
            model_name='communitydetail',
            constraint=models.UniqueConstraint(fields=('language_code', 'community'), name='unique materials in collection'),
        ),
    ]
