# Generated by Django 2.2.7 on 2020-02-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_community_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=16384, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='description',
        ),
        migrations.RemoveField(
            model_name='community',
            name='description_translations',
        ),
        migrations.RemoveField(
            model_name='community',
            name='title_translations',
        ),
        migrations.CreateModel(
            name='CommunityLanguageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=2)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.CommunityDetail')),
            ],
            options={
                'verbose_name': 'Community Detail Translation',
            },
        ),
        migrations.AddField(
            model_name='community',
            name='language_detail',
            field=models.ManyToManyField(blank=True, through='communities.CommunityLanguageDetail', to='communities.CommunityDetail', verbose_name='Language specific details'),
        ),
        migrations.AddConstraint(
            model_name='communitylanguagedetail',
            constraint=models.UniqueConstraint(fields=('language_code', 'community'), name='unique materials in collection'),
        ),
    ]
