const THEME_CATEGORY_FILTER_FIELD = 'learning_material_themes_normalized'
const CONSORTIUM_CATEGORY_FILTER_FIELD = 'consortium'
const PUBLISHER_DATE_FIELD = 'publisher_date'

export {
  THEME_CATEGORY_FILTER_FIELD,
  CONSORTIUM_CATEGORY_FILTER_FIELD,
  PUBLISHER_DATE_FIELD,
}
