/**
 * This file is the middleware.js file that gets generated by NuxtJS.
 * Other code uses the middleware object created here, but remove this file when all dependencies are gone.
 */

let middleware = {};

export default middleware
