# Generated by Django 2.0.6 on 2018-12-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_auto_20181116_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='materials_count',
            field=models.IntegerField(default=0),
        ),
    ]
