# Generated by Django 2.0.8 on 2019-01-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0004_filter_materials_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercategoryitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
