# Generated by Django 2.0.13 on 2019-08-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0007_mpttfilteritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttfilteritem',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Field id in EduRep'),
        ),
        migrations.AlterField(
            model_name='mpttfilteritem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
