# Generated by Django 2.0.13 on 2019-08-29 14:37

from django.db import migrations
import datetime
from surf.apps.filters.utils import check_and_update_mptt_filters

from surf.apps.filters.models import MpttFilterItem
from surf.apps.locale.models import Locale
from surf.vendor.edurep.xml_endpoint.v1_2.api import LANGUAGE_FIELD_ID


def migrate_filter_categories_to_mptt(apps, schema_editor):
    FilterCategory = apps.get_model('filters', 'FilterCategory')
    for filter_category in FilterCategory.objects.all():
        print(filter_category.title)
        if not filter_category.title_translations:
            translation = Locale.objects.create(
                asset=f"{filter_category.title}_auto_generated_at_{datetime.datetime.now().strftime('%c')}",
                en=filter_category.title, nl=filter_category.title, is_fuzzy=True)
        else:
            translation = Locale.objects.get(id=filter_category.title_translations.id)

        root_node = MpttFilterItem.objects.create(name=filter_category.title, title_translations=translation,
                                                  external_id=filter_category.edurep_field_id)
        if filter_category.edurep_field_id == LANGUAGE_FIELD_ID:
            translation_en = Locale.objects.create(
                asset=f"{'en'}_auto_generated_at_{datetime.datetime.now().strftime('%c')}",
                en='en', nl='en', is_fuzzy=False)
            MpttFilterItem.objects.create(name='en', title_translations=translation_en, parent=root_node,
                                          external_id='en')
            translation_nl = Locale.objects.create(
                asset=f"{'nl'}_auto_generated_at_{datetime.datetime.now().strftime('%c')}",
                en='nl', nl='nl', is_fuzzy=False)
            MpttFilterItem.objects.create(name='nl', title_translations=translation_nl, parent=root_node,
                                          external_id='nl')

    check_and_update_mptt_filters()


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0007_mpttfilteritem'),
    ]

    operations = [
        migrations.RunPython(migrate_filter_categories_to_mptt)
    ]
