# Generated by Django 2.0.13 on 2019-08-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0008_auto_20190815_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpttfilteritem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
