# Generated by Django 2.0.13 on 2019-08-30 13:29

from django.db import migrations

def clone_filter_items_to_mptt(apps, schema_editor):
    FilterItem = apps.get_model('filters', 'FilterItem')
    MpttFilterItem = apps.get_model('filters', 'MpttFilterItem')

    for filter_item in FilterItem.objects.all():
        title = filter_item.category_item.title
        mpttfilter = MpttFilterItem.objects.get(name=title)
        filter_item.mptt_category_item = mpttfilter
        filter_item.save()


def undo_clone(apps, schema_editor):
    FilterItem = apps.get_model('filters', 'FilterItem')
    for filter_item in FilterItem.objects.all():
        filter_item.mptt_category_item = None
        filter_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0009_filteritem_mptt_category_item'),
    ]

    operations = [
        migrations.RunPython(clone_filter_items_to_mptt, undo_clone)
    ]
