# Generated by Django 2.0.13 on 2019-09-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0010_auto_20190830_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpttfilteritem',
            options={'verbose_name': 'filter category item'},
        ),
    ]
