# Generated by Django 2.2.13 on 2020-08-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS querylog_querylog;')
    ]
