# Generated by Django 3.2.8 on 2022-03-16 09:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locale', '0004_improved_translations'),
        ('filters', '0001_squashed_0016_filters_external_id_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=255)),
                ('description_translations', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.localehtml')),
                ('title_translations', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.locale')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='parent_themes', to='filters.MpttFilterItem')),
                ('filter_category_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='filters.mpttfilteritem')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('en_slug', models.SlugField(max_length=100, null=True)),
                ('nl_slug', models.SlugField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='filter_category_item',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='title_translations',
        ),
    ]
