# Generated by Django 2.0.6 on 2018-11-17 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filters', '0003_auto_20181116_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=255, verbose_name='Filter item id in EduRep')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='parent_themes', to='filters.FilterCategoryItem')),
                ('filter_category_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='filters.FilterCategoryItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
