# Generated by Django 3.2.8 on 2022-01-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_squashed_0007_predictable_theme_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='en_slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='nl_slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
