# Generated by Django 3.2.14 on 2022-07-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_squashed_0004_strip_themes_and_disciplines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
