# Generated by Django 2.0.6 on 2018-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='external_id',
            field=models.CharField(max_length=255),
        ),
    ]
