# Generated by Django 3.2.8 on 2021-12-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_update_themes_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='filter_category_item',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='title_translations',
        ),
    ]
