# Generated by Django 2.0.13 on 2019-07-17 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('search_text', models.TextField()),
                ('filters', models.TextField()),
                ('query_url', models.TextField()),
                ('result_size', models.IntegerField()),
                ('result', models.TextField()),
            ],
        ),
    ]
