# Generated by Django 2.2.13 on 2020-10-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querylog', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS querylog_querylog;')
    ]
