# Generated by Django 2.2.13 on 2020-11-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anatomytooloaipmh',
            name='set_specification',
        ),
    ]
