# Generated by Django 3.2.14 on 2022-08-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('metadata', '0003_disciplines_and_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatavalue',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
