from search.views.document import DocumentSearchAPIView, DocumentSearchDetailAPIView, DocumentSearchDetailsAPIView
from search.views.autocomplete import AutocompleteAPIView
from search.views.similarity import SimilarityAPIView, AuthorSuggestionsAPIView
from search.views.stats import SearchStatsAPIView
