# Generated by Django 2.0.10 on 2019-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='nl',
            field=models.CharField(blank=True, max_length=5120, null=True, verbose_name='Dutch, nl-NL'),
        ),
    ]
