# Generated by Django 2.0.6 on 2018-11-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_viewmaterial_viewed_at'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='communities', to='materials.Collection'),
        ),
    ]
