# Generated by Django 2.2.13 on 2021-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_squashed_0013_update_title_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='search_query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
