# Generated by Django 3.2.4 on 2021-08-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='publisher',
            field=models.CharField(blank=True, help_text='Publisher name that published most materials in this community. Powers community search.', max_length=255, null=True),
        ),
    ]
