# Generated by Django 2.0.6 on 2018-12-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_create_surf_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SurfConext group id'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
