# Generated by Django 3.2.8 on 2022-03-16 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydetail',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='communities', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='communitydetail',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='communities', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
