# Generated by Django 3.2.14 on 2022-10-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_community_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydetail',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
