# Generated by Django 2.0.13 on 2019-08-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locale', '0004_improved_translations'),
        ('communities', '0006_auto_20190801_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description_translations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.LocaleHTML'),
        ),
        migrations.AddField(
            model_name='community',
            name='title_translations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='locale.Locale'),
        ),
    ]
