# Generated by Django 2.2.13 on 2020-07-14 13:24

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_update_meta_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydetail',
            name='title',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1)]),
        )
    ]
