name: Harvester CI

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    env:
      AWS_ACCESS_KEY_ID: AKIA4VLUZ2543W42M7M7
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-central-1"
      APPLICATION_CONTEXT: unprivileged
      APPLICATION_MODE: localhost
      POL_POSTGRES_HOST: 127.0.0.1

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: edushare
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: psycopg2 prerequisites
      run: sudo apt-get install python3-dev libpq-dev gettext
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install git+https://github.com/surfedushare/search-client.git@v0.3.0
    - name: Setup repository
      run: |
        invoke aws.sync-repository-state --no-profile --bucket-prefix=nppo-prod
    - name: Run tests
      run:
        invoke test.harvester
